(()=>{'use strict';
const USERS={
'990001':{pin:'314159',name:'Monserrat Cayon',title:'UAT Full-Cycle Reviewer',department:'IC Admin',roles:['Employee','Manager','Administrator']},
'990002':{pin:'253614',name:'Gabriel Sabogal',title:'VP Corporate LATAM / Managing Director Mexico',department:'Executive Management',roles:['Employee','Manager','Administrator']},
'267476':{pin:'476826',name:'Jose Antonio Garcia Santiago',title:'Officer Success Representative',department:'Officer Success',roles:['Employee']},
'257270':{pin:'270642',name:'Deysi Salas Figueroa',title:'Employee Relations Team Lead',department:'People Operations',roles:['Employee']}
};
const COMPETENCIES=['Effective Communication','Adaptability and Initiative','Role Mastery','Processes and Tools','Results Orientation','Planning and Organization'];
const GOALS=[
{title:'Reduce internal request response time',target:'15% reduction',result:'18% reduction achieved',achievement:120},
{title:'Update department records',target:'100% updated',result:'95% completed',achievement:95},
{title:'Implement a monthly follow-up dashboard',target:'Live by month two',result:'Launched during month two',achievement:100}
];
const app=document.getElementById('app');
const session=()=>JSON.parse(sessionStorage.getItem('edd-v2-session')||'null');
function login(){app.innerHTML='<div class="shell"><div class="top"><div class="brand">INTER-CON · PERFORMANCE</div><div class="badge">STG V2</div></div><div class="login"><div class="eyebrow">IC ADMIN · PERFORMANCE MANAGEMENT</div><h1>Welcome</h1><p class="muted">Sign in to continue to the native-English staging experience.</p><label class="field"><span>Employee number</span><input id="employee" inputmode="numeric" autocomplete="username"></label><label class="field"><span>Access PIN</span><input id="pin" type="password" inputmode="numeric" autocomplete="current-password"></label><button class="btn" id="go">Sign in</button><div id="error" class="error"></div></div></div>';document.getElementById('go').onclick=()=>{const id=document.getElementById('employee').value.trim(),pin=document.getElementById('pin').value.trim(),u=USERS[id];if(!u||u.pin!==pin){document.getElementById('error').textContent='Incorrect employee number or PIN.';return}sessionStorage.setItem('edd-v2-session',JSON.stringify({id}));dashboard()}}
function demoData(id){const k='edd-v2-demo-'+id;let d=JSON.parse(localStorage.getItem(k)||'null');if(!d){d={self:[5,4,4,4,5,4],manager:[5,5,4,4,5,4],selfComment:'I delivered consistently against my core responsibilities and improved visibility through structured follow-up.',strengths:'Ownership, collaboration, reliable delivery, and clear communication.',development:'Increase cross-functional visibility and strengthen planning for higher-impact initiatives.',managerComment:'Strong ownership and dependable execution. Continue developing prioritization and proactive stakeholder communication.',calibration:'The manager result is confirmed after reviewing documented evidence and outcomes.',agreements:'Maintain monthly development check-ins and lead one cross-functional improvement initiative during the next cycle.',managerSigned:false,employeeSigned:false};localStorage.setItem(k,JSON.stringify(d))}return d}
function saveData(id,d){localStorage.setItem('edd-v2-demo-'+id,JSON.stringify(d))}
function dashboard(){const s=session(),u=s&&USERS[s.id];if(!u)return login();app.innerHTML='<div class="shell"><div class="top"><div class="brand">INTER-CON · PERFORMANCE</div><div><span class="badge">STG V2</span> &nbsp; <button id="out">Sign out</button></div></div><main class="wrap"><section class="hero"><div><div class="eyebrow">PERFORMANCE CYCLE · FY2026</div><h1>'+u.name+'</h1><div class="muted">'+u.title+' · '+u.department+'</div></div><div class="muted">Roles: '+u.roles.join(' · ')+'</div></section><section class="cards"><div class="card"><span class="muted">Self-assessment</span><b>100%</b><small>Completed</small></div><div class="card"><span class="muted">Manager review</span><b>4.3</b><small>Average rating</small></div><div class="card"><span class="muted">Goals</span><b>3</b><small>Cycle goals</small></div><div class="card"><span class="muted">Overall progress</span><b>72%</b><small>Current workflow</small></div></section><section class="panel"><div class="eyebrow">FULL PERFORMANCE WORKFLOW</div><h2>Evaluation journey</h2><p class="muted">V2 is being rebuilt as an English-native product. No translation layer is used.</p><div class="steps"><button class="step active" data-view="self">Self-assessment</button><button class="step active" data-view="manager">Manager review</button><button class="step active" data-view="calibration">OD calibration</button><button class="step active" data-view="feedback">Feedback</button><button class="step active" data-view="signatures">Signatures</button></div></section><section class="panel"><div class="eyebrow">DEMO DATASET</div><h2>Functional staging scenario</h2><p>Strengths, development opportunities, goals, manager comments, calibration rationale, meeting confirmation, agreements and signatures will be seeded directly in English for end-to-end UAT.</p></section></main></div>';document.getElementById('out').onclick=()=>{sessionStorage.removeItem('edd-v2-session');login()};document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>detail(x.dataset.view))}
function detail(view){const s=session(),u=s&&USERS[s.id];if(!u)return login();const d=demoData(s.id);let content='';
if(view==='self')content='<div class="eyebrow">EMPLOYEE · SELF-ASSESSMENT</div><h1>Performance self-assessment</h1>'+COMPETENCIES.map((x,i)=>'<div class="card"><b>'+x+'</b><p class="muted">Current rating: '+d.self[i]+' / 5</p></div>').join('')+'<div class="panel"><h2>Overall reflection</h2><p>'+d.selfComment+'</p></div>';
if(view==='manager')content='<div class="eyebrow">MANAGER REVIEW</div><h1>Manager evaluation</h1>'+COMPETENCIES.map((x,i)=>'<div class="card"><b>'+x+'</b><p>Employee '+d.self[i]+' / 5 · Manager '+d.manager[i]+' / 5</p></div>').join('')+'<div class="panel"><h2>Qualitative summary</h2><p><b>Strengths:</b> '+d.strengths+'</p><p><b>Development opportunities:</b> '+d.development+'</p><p><b>Manager comments:</b> '+d.managerComment+'</p></div><div class="panel"><h2>Goal validation</h2>'+GOALS.map(g=>'<p><b>'+g.title+'</b><br>Target: '+g.target+' · Result: '+g.result+' · '+g.achievement+'% achievement</p>').join('')+'</div>';
if(view==='calibration')content='<div class="eyebrow">ORGANIZATIONAL DEVELOPMENT</div><h1>Calibration</h1><div class="panel"><h2>Calibrated result: 4.4 / 5</h2><p>'+d.calibration+'</p></div>';
if(view==='feedback')content='<div class="eyebrow">FEEDBACK MEETING</div><h1>Feedback and agreements</h1><div class="panel"><h2>Meeting confirmed</h2><p><b>Final agreements:</b> '+d.agreements+'</p></div>';
if(view==='signatures')content='<div class="eyebrow">CYCLE CLOSURE</div><h1>Signatures</h1><div class="panel"><h2>Manager signature</h2><p>'+(d.managerSigned?'Signed':'Pending')+'</p><button class="btn" id="managerSign">Sign as manager</button></div><div class="panel"><h2>Employee signature</h2><p>'+(d.employeeSigned?'Signed':'Pending')+'</p><button class="btn" id="employeeSign">Sign as employee</button></div>';
app.innerHTML='<div class="shell"><div class="top"><div class="brand">INTER-CON · PERFORMANCE</div><div><span class="badge">STG V2</span> &nbsp; <button id="back">Back</button></div></div><main class="wrap">'+content+'</main></div>';document.getElementById('back').onclick=dashboard;
if(view==='signatures'){managerSign.onclick=()=>{d.managerSigned=true;saveData(s.id,d);detail(view)};employeeSign.onclick=()=>{if(!d.managerSigned)return;d.employeeSigned=true;saveData(s.id,d);detail(view)}}}
session()?dashboard():login();
})();