(()=>{'use strict';
const USERS={
'990001':{pin:'314159',name:'Monserrat Cayon',title:'UAT Full-Cycle Reviewer',department:'IC Admin',roles:['Employee','Manager','Administrator']},
'990002':{pin:'253614',name:'Gabriel Sabogal',title:'VP Corporate LATAM / Managing Director Mexico',department:'Executive Management',roles:['Employee','Manager','Administrator']},
'267476':{pin:'476826',name:'Jose Antonio Garcia Santiago',title:'Officer Success Representative',department:'Officer Success',roles:['Employee']},
'257270':{pin:'270642',name:'Deysi Salas Figueroa',title:'Employee Relations Team Lead',department:'People Operations',roles:['Employee']}
};
const app=document.getElementById('app');
const session=()=>JSON.parse(sessionStorage.getItem('edd-v2-session')||'null');
function login(){app.innerHTML='<div class="shell"><div class="top"><div class="brand">INTER-CON · PERFORMANCE</div><div class="badge">STG V2</div></div><div class="login"><div class="eyebrow">IC ADMIN · PERFORMANCE MANAGEMENT</div><h1>Welcome</h1><p class="muted">Sign in to continue to the native-English staging experience.</p><label class="field"><span>Employee number</span><input id="employee" inputmode="numeric" autocomplete="username"></label><label class="field"><span>Access PIN</span><input id="pin" type="password" inputmode="numeric" autocomplete="current-password"></label><button class="btn" id="go">Sign in</button><div id="error" class="error"></div></div></div>';document.getElementById('go').onclick=()=>{const id=document.getElementById('employee').value.trim(),pin=document.getElementById('pin').value.trim(),u=USERS[id];if(!u||u.pin!==pin){document.getElementById('error').textContent='Incorrect employee number or PIN.';return}sessionStorage.setItem('edd-v2-session',JSON.stringify({id}));dashboard()}}
function dashboard(){const s=session(),u=s&&USERS[s.id];if(!u)return login();app.innerHTML='<div class="shell"><div class="top"><div class="brand">INTER-CON · PERFORMANCE</div><div><span class="badge">STG V2</span> &nbsp; <button id="out">Sign out</button></div></div><main class="wrap"><section class="hero"><div><div class="eyebrow">PERFORMANCE CYCLE · FY2026</div><h1>'+u.name+'</h1><div class="muted">'+u.title+' · '+u.department+'</div></div><div class="muted">Roles: '+u.roles.join(' · ')+'</div></section><section class="cards"><div class="card"><span class="muted">Self-assessment</span><b>100%</b><small>Completed</small></div><div class="card"><span class="muted">Manager review</span><b>4.3</b><small>Average rating</small></div><div class="card"><span class="muted">Goals</span><b>3</b><small>Cycle goals</small></div><div class="card"><span class="muted">Overall progress</span><b>72%</b><small>Current workflow</small></div></section><section class="panel"><div class="eyebrow">FULL PERFORMANCE WORKFLOW</div><h2>Evaluation journey</h2><p class="muted">V2 is being rebuilt as an English-native product. No translation layer is used.</p><div class="steps"><div class="step active">Self-assessment</div><div class="step active">Manager review</div><div class="step active">OD calibration</div><div class="step">Feedback</div><div class="step">Manager signature</div><div class="step">Employee signature</div></div></section><section class="panel"><div class="eyebrow">DEMO DATASET</div><h2>Functional staging scenario</h2><p>Strengths, development opportunities, goals, manager comments, calibration rationale, meeting confirmation, agreements and signatures will be seeded directly in English for end-to-end UAT.</p></section></main></div>';document.getElementById('out').onclick=()=>{sessionStorage.removeItem('edd-v2-session');login()}}
session()?dashboard():login();
})();